version: '3'

volumes:
  mysql-data:
  es-data:

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: base-magento
        restart: always
        ports:
            - "80:80"   

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        volumes:
            - ./.artifakt/conf/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf:ro
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_USER: artifakt_magento
            MYSQL_PASSWORD: artifakt_magento
            MYSQL_ROOT_PASSWORD: artifakt_magento
            MYSQL_DATABASE: artifakt_magento
        ports:
            - "3306:3306"

    redis:
        image: redis:6.0-alpine
        container_name: redis
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./.artifakt/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
        ports:
            - "6379:6379"
            
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        container_name: elasticsearch
        restart: always
        environment:
            - node.name=es01
            - discovery.type=single-node
            - bootstrap.memory_lock=true
        volumes:
            - es-data:/usr/share/elasticsearch/data:rw
        ports:
            - "9200:9200"
            - "9300:9300"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
