version: '3'

services:
  redis:
    image: redis:6.0-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: '-Xms512M -Xmx512M'
      discovery.type: 'single-node'
    ulimits:
        nofile:
           soft: 65536
           hard: 65536

networks:
  default:
    external:
      name: net
